# This rule is not used by the project ghost-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over blog.example.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ghost-operator
    app.kubernetes.io/managed-by: kustomize
  name: ghost-admin-role
rules:
- apiGroups:
  - blog.example.com
  resources:
  - ghosts
  verbs:
  - '*'
- apiGroups:
  - blog.example.com
  resources:
  - ghosts/status
  verbs:
  - get
